### ISSUE TITLE
smartStep isn't found unless also tagged

### ISSUE THREAD

**Issue by sethcohn** [KnpLabs/FriendlyContexts#119]
If you invoke behat with --tags=tagyouwantrun, and the Scenario tagged with @tagyouwanttorun calls a @smartStep scenario as a step, it won't work unless the scenario is also tagged with @tagyouwanttorun.  It will fail and claim it's an undefined step.

**Comment by PedroTroller** [comment]
Of course, it's a tag like others. If you want's to use tag filters and smartstep in a same time.... Don't use smartstep. Or add smartStep to your filter.
