### ISSUE TITLE
Deprecated Symfony 2.7 factory

### ISSUE THREAD

**Issue by riskawarrior** [KnpLabs/FriendlyContexts#152]
Symfony 2.6 introduced a new way to use factories:
http://symfony.com/doc/current/components/dependency_injection/factories.html

The problem is that the old way (<2.6) generates a lot of deprecated messages with Symfony 2.7 which makes impossible the testing in dev mode.

Affected service:
    friendly.faker:
        class: Faker\Generator
        factory_class: Faker\Factory
        factory_method: create

Solution: changing this service to:
    friendly.faker:
        class: Faker\Generator
        factory: [Faker\Factory, create]

**Comment by shopfe** [comment]
This solve the factory deps

**Comment by riskawarrior** [comment]
I messed up the first pull request, this should work. :)

**Comment by akovalyov** [comment]
And what about Symfony <2.6 ? It does not have ```setFactory``` method. You can check it in https://github.com/symfony/DependencyInjection/blob/2.5/Definition.php.
I think, the best solution to keep BC is to handle it via DependencyInjection Compilers.
@PedroTroller what do you think?

**Comment by PedroTroller** [comment]
@akovalyov Or maybe via a bidge class ?

**Comment by riskawarrior** [comment]
It's tough. I took a look at other projects and they used this format (xml):

From this one

    <service id="sonata.admin.entity_manager" factory-service="doctrine" factory-method="getEntityManager" class="Doctrine\ORM\EntityManager" public="false">

To this one:

    <service id="sonata.admin.entity_manager" class="Doctrine\ORM\EntityManager" public="false">
        <factory service="doctrine" method="getEntityManager"/>

They say that it is BC from version 2.3: https://github.com/doctrine/DoctrineBundle/pull/381
