### ISSUE TITLE
Testing APIs with Behat and FriendlyContext

### ISSUE THREAD

**Issue by javierseixas** [KnpLabs/FriendlyContexts#159]
Hi everybody,
I open this issue because I'm not clear on the way that FriendlyContext works for testing data in DB using EntityContext. Before explaining why I'm thinking such a thing, I want to say that I've used FriendlyContext for testing REST APIs and its DBs, and I like it a lot, even I made a bit contribution.

Well, the point is that when I test, for example, a `POST` request which inserts a Resource Product in the database, I test two things:
1. The HTTP response is what I expect
2. In the DB has been stored what I expect

For the first point I use the APIContext, and it works just fine!
For the second point I use the EntityContext and the AliceContext, and it works ok too, but I realised that they use the doctrine mapping and entities that they are supposed to test. I understand that a test battery should tests a system in an independent way. But how EntityContext is working now, an error in the mapping affects both, application and tests.
I'm not saying it is wrong, but I'm wondering if exists a better way of testing what has been stored, or if anybody here tests REST APIs in a different way.

**Comment by PedroTroller** [comment]
Hi @javierseixas, and thanks.

In fact the good way to do it is not to test if your resource is really persisted into your database, it's a lazy solution (because I am lazy :smile:).
I think the good way to do it is : 
 - to test if your application says that the resource is created (201) 
 - to test if your new resource is available, by testing the Content-Location of your 200 and/or by testing that your resource is available when you call your collection.

**Comment by javierseixas** [comment]
Thanks for your reply @PedroTroller 
You are right, I could check a success creation by doing a new request to the resource. The problem of doing this is that, I would be using another functionality (a `GET` request) to test the funcionality I am focus on, a `POST`, so an error in the `GET` would throw an error in the `POST`. Should not we avoid this?
Another drawback I've faced by doing this, is that it makes tests slower, since is necessary to make another HTTP request, which is slower than a DB query.
