### ISSUE TITLE
FriendlyContext existLikeFollowing bug

### ISSUE THREAD

**Issue by jamesyo** [KnpLabs/FriendlyContexts#168]
Hi Everybody!

I'm not sure if this is a bug. Regarding the friendlyContext EntityContext `existLikeFollowing` (line 152). 

The function doesn't seem to be matching on the keys I want it to map on! It seems to be matching on `id`, regardless of what key I supply.

It seems that the function is only matching entities by the doctrine identifiers, where the examples seem to suggest entities will be matched by fields passed to the function ( https://github.com/KnpLabs/FriendlyContexts/blob/master/doc/context-entity.md ).

The function works as it should if, rather than matching the entity by the array created by `getEntityIdentifiers` (line 167), it matches by the `$values` array (line 162).

In my instance, when trying to find a user entity by username, I have a scenario:

```
    Then there should be 1 "User" entity like:
      | username  |
      | DummyUser |
```

`$values` is created as so:

```
$values = {'username' => 'DummyUser'}

```

whereas `getEntityIdentifiers` returns

```
{ 'id' => 'DummyUser'}
```

In order for the `findBy()` call to return the correct object, the `$values` array needs to be used, rather than then array returned by `getEntityIdentifiers()`. 

The array `$values` is created then only used when an exception is thrown, another reason for me to believe it may be a bug.

I hope this makes sense! What do you think?

**Comment by smarques** [comment]
same exact problem here
