### ISSUE TITLE
It is possible to seed the faker to ensure the generated data is always the same

### ISSUE THREAD

**Issue by yakobe** [KnpLabs/FriendlyContexts#171]
I am using the entity context to create data. For fields that are not specified manually it generates fake data. However, this changes every time so the tests might break randomly. After reading the docs i cannot see a way to set the seed to keep generation constant. Is there a way?

**Comment by PedroTroller** [comment]
If you need the same data to run your tests, then you can't use to use the faker feature. If your data are important for your tests, please write them directly, don't let faker generate it for you.

**Comment by yakobe** [comment]
Its not that we always need the same data, and it would help to ba able to set the seed anyway.
Ps: any ideas how to make certain data fake with certain rules? Eg if a field is text but has to be a minimum of 2 chars due to symfony validation. I really dont care about what these chars are for my current test. So i just want alice to throw in some data. Without a seed we get random break where this field is no longer valid. Our application logic is pretty complex, so specifying data for all dependencies would draw focus away from what is actually being tested.

**Comment by PedroTroller** [comment]
The entity context don't use Alice, BUT you can use alice instead of the entity context.
https://github.com/KnpLabs/FriendlyContexts/blob/master/doc/context-alice.md

**Comment by yakobe** [comment]
The entity context seems to use faker... that's why i was wondering if it was possible to set the seed (https://github.com/fzaninotto/Faker#seeding-the-generator)
