### ISSUE TITLE
Unable to parse JSON data: JSON_ERROR_SYNTAX

### ISSUE THREAD

**Issue by taqiofficial** [KnpLabs/FriendlyContexts#221]
I am using BDD tests with FriendlyContexts for my symfony project and got this error, `Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON (InvalidArgumentException)`, I validat the json with http://jsonlint.com/, and it valid. But again when i run it, give the same error.

```
 Scenario: Update booking
    Given I prepare a PUT request on "/booking/v1/book/1"
    Given I specified the following request body:
    """
    {
      "title": "Room #908a",
      "personsCapacity": 6,
      "sequence": 11,
      "image": "http://abc/images/image2.jpg",
      "description": "Nulla vitae elit libero, a pharetra augue."
    }
    """
    When I send the request
    Then I should receive a 200 response
    And the response should contain the following data in json:
    """
    {
      "id": "1",
      "title": "Room #908a",
      "personsCapacity": 6,
      "sequence": 11,
      "image": "http://abc/images/image2.jpg",
      "description": "Nulla vitae elit libero, a pharetra augue."
    }
    """
```

Any Hint Why these ?

**Comment by Einenlum** [comment]
Is the first json code or the second one which crashes?

**Comment by taqiofficial** [comment]
@Einenlum 2nd one.

**Comment by taqiofficial** [comment]
It only appears at some scenarios only, not all. I had compare all those with who are working fine, 100% are same. Can't find anything that causes the Json error.

**Comment by taqiofficial** [comment]
Ok, I got the what's the issue, there was a var_dumper inside code.
But Strange, Normal API response doesn't effect from it, but Gerkin/BDD Context does.
