### ISSUE TITLE
Smart Step feature seems to have major performance problems

### ISSUE THREAD

**Issue by yakobe** [KnpLabs/FriendlyContexts#225]
When there are a large number of features / scenarios the following function can cause huge numbers of calls leading to major performance problems.

> \Knp\FriendlyContexts\Reader\SmartReader::extractScenarios

Unfortunately it is not possible to disable the smart step feature to prevent these problems. At the moment we have a fork where we remove the `environment.reader` service tag on `friendly.reader.smart_reader` in `core.yml` to stop the `SmartReader` from being registered. 

Perjaps there is a way to reduce the performance impact. Alternatively it would be good if there was a way to disable the Smart Step feature.

**Comment by Nek-** [comment]
Hello. Can you be more explicit about what performance problem you have? I never experiment performance outage without using the smart step feature. (that I don't recommend to use precisely because of performance outage)

**Comment by yakobe** [comment]
Hi Nek,
We were puzzled why our complete behats on a large project were taking over 4 hours to run. After using blackfire to profile the problem we discovered that registering the`friendly.reader.smart_reader` triggers code to be fired after all the time while it looks through the scenarios (even if you are not using smart steps anywhere in the code). It seems this lookup is not cached either so it is parsing real files. 

We [forked this repo](https://github.com/netdudes/FriendlyContexts/commit/a0caee9eafaf3d3ff5213f79f43da37b4d86fb56) and disabled this environment reader and our behats ran in half an hour.

Unfortunately i cannot share the blackfire code with you, but if you run it on a larger project you will see what i mean.

**Comment by yakobe** [comment]
PS: we were a bit unsure if the repo was actually maintained anymore as there does not seem to be much activity and we have offered a couple of PR's that never got a response. Should we continue or is this repo semi-abandoned? We would be happy to contribute, but otherwise we would just maintain our own fork.

**Comment by Nek-** [comment]
I'll take a look at the issue. Thanks for reporting and also thanks for the fix. (is it also MIT ?)

About the PS... Until now yes it was semi-abandoned, but I was promoted maintainer, I'll try to make the project move in the right direction :) .

**Comment by yakobe** [comment]
Just so you know, our solution is not a fix. It just disables smart steps it on our fork 😄 . We dont use them anyway. I guess it would be better if the features were disabled by default and you can opt in.

Great new that there is a maintainer again. We will try to provide more help again in the future.

**Comment by lpoczatek** [comment]
https://github.com/KnpLabs/FriendlyContexts/issues/239
