### ISSUE TITLE
Can't use @reset-schema along with @alice

### ISSUE THREAD

**Issue by pierredup** [KnpLabs/FriendlyContexts#234]
I'm trying to reset the database schema, then load a set of fixtures before a scenario, but it seems the `reset-schema` is always run after the fixtures, which cleans the database then.
E.G given the following feature:

```yaml
  @reset-schema
  @alice(Product)
  Scenario: ...
```
When I run behat, I get in error in my scenario (since there is no data) and the database is then empty afterwards. I'm not sure if I'm just missing something

**Comment by Nek-** [comment]
Hello,

Thank you for the report, can you give us more information about the issue? I personally use it on a project today and it works. 😶

**Comment by pierredup** [comment]
@Nek- I actually ended up writing my own `reset-schema` implementation because I needed some additional logic and fixtures to be loaded, and trying to replicate this again might be a lot of effort. So I'm closing this as a non-issue then
