### ISSUE TITLE
EntityContext issue with AfterScenario clearing...

### ISSUE THREAD

**Issue by tsurowiec** [KnpLabs/FriendlyContexts#240]
lets say I have two tests - to simplify identical, but issue happens always, when there is more then one test in a scenario, and the `should have been (created|deleted)` step is used : 

```gherkin
  Background:
    Given the following users:
      | email         | enabled |
      | admin@tsh.io  | 1       |
    And I am authorised as "admin@tsh.io"

  @reset-schema
  Scenario: Add user
    When I send a "POST" request to "/api/v1/users/csr" with body:
      """
        {
          "email": "user1@tsh.io",
        }
      """
    Then the response status code should be 201
    And 1 user should have been created

  @reset-schema
  Scenario: Add user
    When I send a "POST" request to "/api/v1/users/csr" with body:
      """
        {
          "email": "user2@tsh.io",
        }
      """
    Then the response status code should be 201
    And 1 user should have been created
```
when those scenarios are run separately they are ok - both green, but when the whole feature is run, the second scenario's `And 1 user should have been created` step fails with `2 acctually` as if between scenarios, the `EntityContext::afterScenario()` didn't do it's job (it is executed though). 

Is it a known issue, or am I doing wrong sth... ?

**Comment by einenlum** [comment]
Hi @tsurowiec. Thanks for your issue.
I never encountered this problem and I don't remember any issue referencing it. I will try to find time to check what's happening in the next days.

**Comment by tsurowiec** [comment]
thanks@Einenlum, I'll try to replicate it on an minimal Symfony project, and if it still occurs I'll link the repo here...

**Comment by tsurowiec** [comment]
@Einenlum the issue can be closed - I wasn't able to replicate it on fresh install of symfony - means that is nothing wrong with EntityContext, but sth is f%#$ up in the project I've got.

**Comment by einenlum** [comment]
Ok, thanks for your feedback @tsurowiec. Glad to hear that :)
